[package]
name = "patata"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
eframe = "0.28.1"
env_logger = "0.11.5"
log = "0.4.22"
rand = { version = "0.8.5", features = ["std"] }
sdl2 = "0.37.0"
